logging:
  level:
    ROOT: INFO

spring:
  thymeleaf:
    cache: false

  data:
    cassandra:
      keyspace-name: tacocloud
      schema-action: CREATE_IF_NOT_EXISTS
      local-datacenter: datacenter1


